name: Run tests

on: push

jobs:
  run-addon-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: moguri/setup-blender@v1
        id: install-blender
        with:
          blender-version: "4.2"
      - run: blender --version
      - run: python -m pip install --upgrade pip
      - run: |
          pip install pytest-blender pytest
          echo '${{steps.install-blender.outputs.blender-path}}'
      - run: pytest tests/
