name: Run tests

on: push

jobs:
  run-addon-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: moguri/setup-blender@v1
        with:
          blender-version: "4.2"
      - run: blender --version
      - run: python -m pip install --upgrade pip
      - run: |
          pip install pytest-blender
          python_blender_executable="$(pytest-blender --blender-executable $blender_executable)"
          $python_blender_executable -m ensurepip
          $python_blender_executable -m pip install pytest
      - run: pytest tests/
